//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.06 at 05:30:53 PM CEST 
//


package sk.octopuss.moro.mcrws.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cardInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cardInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="panToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="partnerBankCard" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="cardStatus" type="{http://octopuss.sk/moro/mcrws/ws}cardState"/>
 *         &lt;element name="cardVerificationStatus" type="{http://octopuss.sk/moro/mcrws/ws}cardVerificationState"/>
 *         &lt;element name="userAccount" type="{http://octopuss.sk/moro/mcrws/ws}userAccount"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cardInfo", propOrder = {
    "panToken",
    "partnerBankCard",
    "cardStatus",
    "cardVerificationStatus",
    "userAccount"
})
public class CardInfo {

    @XmlElement(required = true)
    protected String panToken;
    protected boolean partnerBankCard;
    @XmlElement(required = true)
    protected CardState cardStatus;
    @XmlElement(required = true)
    protected CardVerificationState cardVerificationStatus;
    @XmlElement(required = true)
    protected UserAccount userAccount;

    /**
     * Gets the value of the panToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPanToken() {
        return panToken;
    }

    /**
     * Sets the value of the panToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPanToken(String value) {
        this.panToken = value;
    }

    /**
     * Gets the value of the partnerBankCard property.
     * 
     */
    public boolean isPartnerBankCard() {
        return partnerBankCard;
    }

    /**
     * Sets the value of the partnerBankCard property.
     * 
     */
    public void setPartnerBankCard(boolean value) {
        this.partnerBankCard = value;
    }

    /**
     * Gets the value of the cardStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CardState }
     *     
     */
    public CardState getCardStatus() {
        return cardStatus;
    }

    /**
     * Sets the value of the cardStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardState }
     *     
     */
    public void setCardStatus(CardState value) {
        this.cardStatus = value;
    }

    /**
     * Gets the value of the cardVerificationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CardVerificationState }
     *     
     */
    public CardVerificationState getCardVerificationStatus() {
        return cardVerificationStatus;
    }

    /**
     * Sets the value of the cardVerificationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardVerificationState }
     *     
     */
    public void setCardVerificationStatus(CardVerificationState value) {
        this.cardVerificationStatus = value;
    }

    /**
     * Gets the value of the userAccount property.
     * 
     * @return
     *     possible object is
     *     {@link UserAccount }
     *     
     */
    public UserAccount getUserAccount() {
        return userAccount;
    }

    /**
     * Sets the value of the userAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAccount }
     *     
     */
    public void setUserAccount(UserAccount value) {
        this.userAccount = value;
    }

}
