//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.06 at 05:30:53 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://octopuss.sk/moro/mcrws/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sk.octopuss.moro.mcrws.ws;
